# Generated by Django 5.0.3 on 2025-09-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_desc', models.TextField(max_length=2000, verbose_name='Описание')),
                ('item_photo', models.ImageField(upload_to='media/', verbose_name='Фото события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, verbose_name='Категория')),
                ('category_desc', models.TextField(default='default', max_length=2000, null=True, verbose_name='Описание категории')),
                ('category_photo', models.ImageField(upload_to='media/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('last_updated_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Последнее обновление')),
                ('status', models.CharField(choices=[('NEW', 'новый'), ('IN_PROGRESS', 'в процессе'), ('DONE', 'исполнен')], max_length=20, verbose_name='Статус')),
                ('delivery_address', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Адрес доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='tg id')),
                ('tg_name', models.TextField(blank=True, default='default', null=True, verbose_name='имя tg')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TeaItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250, verbose_name='Название')),
                ('item_desc', models.TextField(max_length=2000, verbose_name='Описание')),
                ('item_price_idr', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена в IDR')),
                ('item_price_thb', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена в THB')),
                ('item_price_aed', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена в AED')),
                ('item_price_rub', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Цена в RUB')),
                ('item_weight', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вес')),
                ('item_photo', models.ImageField(upload_to='media/', verbose_name='Фото')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Чай и посуда',
                'verbose_name_plural': 'Чай и посуда',
                'db_table': 'tea_items',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default='0.000', null=True, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('currency', models.CharField(max_length=250, null=True, verbose_name='Валюта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.orders', verbose_name='Заказ')),
                ('tea_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.teaitems', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Заказанный товар',
                'verbose_name_plural': 'Заказанные товары',
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.users', verbose_name='Юзер'),
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('currency', models.CharField(max_length=250, null=True, verbose_name='Валюта')),
                ('tea_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.teaitems', verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
                'db_table': 'cards',
            },
        ),
    ]
