# Generated by Django 5.0.3 on 2025-09-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='item_photo',
            field=models.ImageField(upload_to='', verbose_name='Фото события'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teaitems',
            name='item_photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
